sudo: required
services:
    - docker

before_install:
    - docker build -t vneekhra/docker-react-client -f Dockerfile.dev .

script:
    - docker run -e CI=true vneekhra/docker-react-client npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react-client"
    env: "DockerReactClient-env"
    bucket_name: elasticbeanstalk-us-east-2-424816399131
    bucket_path: "docker-react-client"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"